# Model configuration and KD
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
teacher_model_name_or_path: deepseek-ai/DeepSeek-R1-Distill-Llama-8B
kd_ratio: 0.5

# Training methodology
stage: sft
do_train: true
finetuning_type: full

deepspeed: examples/deepspeed/ds_z2_config.json  # options: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

# Dataset configuration
dataset: identity,alpaca_en_demo
template: llama3
cutoff_len: 2048
max_samples: 10000
overwrite_cache: false
preprocessing_num_workers: 16

# Output configuration
output_dir: saves/llama3-8b/full/kd
logging_steps: 10
save_steps: 100
plot_loss: false
overwrite_output_dir: true

# Training parameters
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 2e-05
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
