# Model configuration and KD
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct


# Training methodology
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 32
lora_target: all
deepspeed: examples/deepspeed/ds_z2_config.json  # options: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

# Dataset configuration
dataset: identity,alpaca_en_demo
template: llama3
cutoff_len: 2048
max_samples: 1000
overwrite_cache: false
preprocessing_num_workers: 16

# Output configuration
output_dir: saves/llama3-8b/lora/lora
logging_steps: 10
save_steps: 100
plot_loss: false
overwrite_output_dir: true

# Training parameters
per_device_train_batch_size: 16
gradient_accumulation_steps: 4
learning_rate: 0.0001
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
